### ISSUE TITLE
Automatic update does not set executable bit on tmc.new, fails to run

### ISSUE THREAD

**Issue by varesa** [testmycode/tmc-cli#220]
The update process for `tmc-cli` does not set the executable bit for the newly downloaded `tmc.new` binary so it fails to execute.

```
[esa@esaf ~]$ tmc
A new version of tmc-cli is available!
Do you want to download it? (y/N): y
Downloading...
Failed to run the tmc-cli at /home/esa/tmc.new
Run it with ?internal-update argument or contact the help desk
Usage: tmc [args] COMMAND [command-args]
...


[esa@esaf ~]$ /home/esa/tmc.new
-bash: /home/esa/tmc.new: Permission denied

[esa@esaf ~]$ ls -l /home/esa/tmc.new
-rw-rw-r--. 1 esa esa 20326785 Jun  9 19:45 /home/esa/tmc.new

[esa@esaf ~]$ chmod +x tmc.new

[esa@esaf ~]$ /home/esa/tmc.new
Usage: tmc [args] COMMAND [command-args]
...
```

Sidequestion: 
What is `?internal-update argument`?

```
[esa@esaf ~]$ /home/esa/tmc.new ?internal-update
Command ?internal-update doesn't exist.

[esa@esaf ~]$ /home/esa/tmc.new internal-update
Command internal-update doesn't exist.

[esa@esaf ~]$ /home/esa/tmc.new --internal-update
Invalid command line arguments.
Unrecognized option: --internal-update
```

**Comment by Salmela** [comment]
We had to fix the auto-update code in latest release. Unfortunately the old versions can't update the binary automatically.

As you may have noticed the `tmc-cli` is implemented in java, but it's launched from bash script. The launch script hooks up the auto-completion and alias into the bashrc file. And so it's the bash script's responsibility to swap the old file's into the newer version's files.

The `?internal-update` argument is given to the launch script to signal it to start the auto-update. In the newer version I renamed it as `++internal-update`. Users should never need to use it, but as you have noticed it could be better documented.

But thanks for your bug report. I will check that the permission setting code that it actually works. The older versions didn't even have it, but I am not sure does it work even in the newest version. It's bit hard to test it because in our development machines, every file has user's execution permission set. It's a file system problem that we have no control over.

Thanks also for your persistence to try our Tmc client. Believe it or not it actually works pretty well in our machines.

**Comment by Salmela** [comment]
I am fairly sure that the auto-updates should work in the newest version. If they won't then please open new issue.
